integrated AIX packaging fixes from dev-folti
Patches applied:

 * devel@balabit.hu--other-1/syslog-ng--dev-folti--2.0--patch-2
   Fixed: AIX5.2 packaging support. (fixes: #10375)

 * devel@balabit.hu--other-1/syslog-ng--dev-folti--2.0--patch-3
   Fixes: added libevtlog-dev build dependency. (fixes: #10375)

 * devel@balabit.hu--other-1/syslog-ng--dev-folti--2.0--patch-5
   Fixed: RPM packaging for 2.0. (fixes: #nobug)

 * devel@balabit.hu--other-1/syslog-ng--dev-folti--2.0--patch-7
   Refresh: Fixed: AIX5.2 packaging support. (fixes: #10375)

 * devel@balabit.hu--other-1/syslog-ng--dev-folti--2.0--patch-8
   Refresh: Fixes: added libevtlog-dev build dependency. (fixes: #10375)

 * devel@balabit.hu--other-1/syslog-ng--dev-folti--2.0--patch-9
   Refresh: Fixed: RPM packaging for 2.0. (fixes: #nobug)

 * devel@balabit.hu--other-1/syslog-ng--dev-folti--2.0--patch-10
   Fixed: removed duplicated install commanands from spec file. (fixes #nobug)

diff --git a/syslog-ng.spec.bb.in b/syslog-ng.spec.bb.in
--- a/syslog-ng.spec.bb.in
+++ b/syslog-ng.spec.bb.in
@@ -9,14 +9,19 @@ License: GPL
 Group: System Environment/Daemons
 Source: syslog-ng_%{version}.tar.gz
 URL: http://www.balabit.com
-Packager: Sandor Geller <wildy@balabit.com>
+Packager: Tamas Pal <folti@balabit.com>
 Vendor: Balabit IT Ltd.
 BuildRoot: %{_tmppath}/%{name}-root
-BuildRequires: bison, flex, gcc-c++
+BuildRequires: bison, flex, gcc-c++, pkgconfig, glib2-devel, libevtlog-devel
+Provides: syslog
 #BuildConflicts:
 #Exclusivearch: i386
 
+%ifarch ppc
+%define prefix /opt/freeware
+%else
 %define prefix /
+%endif
 
 %description
  Syslog-ng is a next generation system logger daemon which provides more
@@ -30,65 +35,196 @@ BuildRequires: bison, flex, gcc-c++
 
 # build syslog-ng using the bundled libol
 
-./configure --prefix=/ --mandir=/usr/share/man --infodir=/usr/share/info \
-  --sysconfdir=/etc
+./configure --prefix=%{prefix} --mandir=%{_mandir} --infodir=%{prefix}/share/info \
+  --sysconfdir=/etc/syslog-ng
 make
 
 %install
+# pre install cleaning. for testing only.
+[ $RPM_BUILD_ROOT = / ] || rm -rf $RPM_BUILD_ROOT
 make install DESTDIR="$RPM_BUILD_ROOT"
 # strip the binaries/ libraries
-strip ${RPM_BUILD_ROOT}/sbin/syslog-ng
-#if [ -r /etc/redhat-release ]; then
-#	if grep -q "Red Hat Enterprise Linux ES" /etc/redhat-release; then
-		install -D -o root -g root -m 0644 contrib/rhel-packaging/syslog-ng.conf \
-		  ${RPM_BUILD_ROOT}/etc/syslog-ng/syslog-ng.conf
-		install -D -o root -g root -m 0755 contrib/rhel-packaging/syslog-ng.init \
-		  ${RPM_BUILD_ROOT}/etc/rc.d/init.d/syslog-ng
-		install -D -o root -g root -m 0644 contrib/rhel-packaging/syslog-ng.logrotate \
-		  ${RPM_BUILD_ROOT}/etc/logrotate.d/syslog-ng
-#	fi
-#fi
+strip ${RPM_BUILD_ROOT}/%{prefix}/sbin/syslog-ng
+
+./install-sh -d ${RPM_BUILD_ROOT}/etc/syslog-ng
+./install-sh -d ${RPM_BUILD_ROOT}/etc/rc.d/init.d
+
+if [ "%{_host_vendor}" = "redhat" ]; then
+ ./install-sh -o root -g root -m 0755 contrib/rhel-packaging/syslog-ng.init \
+   ${RPM_BUILD_ROOT}/etc/rc.d/init.d/syslog-ng
+elif [ "%{_host_vendor}" = "suse" ]; then
+ ./install-sh -o root -g root -m 0755 contrib/init.d.SuSE \
+   ${RPM_BUILD_ROOT}/etc/rc.d/init.d/syslog-ng
+fi
+ 
+if [ "%{_host_vendor}" = "ibm" ];then
+ ./install-sh -o root -g bin -m 0644 contrib/aix-packaging/syslog-ng.conf \
+    ${RPM_BUILD_ROOT}/%{prefix}/etc/syslog-ng/syslog-ng.conf
+elif [ "%{_host_vendor}" = "redhat" ] || [ "%{_host_vendor}" = "suse" ]; then
+  install -o root -g root -m 0644 contrib/rhel-packaging/syslog-ng.conf \
+    ${RPM_BUILD_ROOT}/etc/syslog-ng/syslog-ng.conf
+  install -D -o root -g root -m 0644 contrib/rhel-packaging/syslog-ng.logrotate \
+    ${RPM_BUILD_ROOT}/etc/logrotate.d/syslog-ng
+fi
+
 # install documentation
-install -D -o root -g root -m 0644 doc/reference/syslog-ng.html.tar.gz \
-  ${RPM_BUILD_ROOT}/usr/share/doc/syslog-ng-@VERSION@/syslog-ng.html.tar.gz
-install -D -o root -g root -m 0644 doc/reference/syslog-ng.txt \
-  ${RPM_BUILD_ROOT}/usr/share/doc/syslog-ng-@VERSION@/syslog-ng.txt
-install -D -o root -g root -m 0644 ChangeLog \
-  ${RPM_BUILD_ROOT}/usr/share/doc/syslog-ng-@VERSION@/ChangeLog
-install -D -o root -g root -m 0644 NEWS \
-  ${RPM_BUILD_ROOT}/usr/share/doc/syslog-ng-@VERSION@/NEWS
-install -D -o root -g root -m 0644 README \
-  ${RPM_BUILD_ROOT}/usr/share/doc/syslog-ng-@VERSION@/README
-install -D -o root -g root -m 0644 AUTHORS \
-  ${RPM_BUILD_ROOT}/usr/share/doc/syslog-ng-@VERSION@/AUTHORS
-install -D -o root -g root -m 0644 COPYING \
-  ${RPM_BUILD_ROOT}/usr/share/doc/syslog-ng-@VERSION@/COPYING
+[ -d "${RPM_BUILD_ROOT}/%{_prefix}/share/doc/syslog-ng-@VERSION@" ] || ./install-sh -d "${RPM_BUILD_ROOT}/%{_prefix}/share/doc/syslog-ng-@VERSION@"
+./install-sh -o root -g root -m 0644 doc/reference/syslog-ng.html.tar.gz \
+  ${RPM_BUILD_ROOT}/%{_prefix}/share/doc/syslog-ng-@VERSION@/syslog-ng.html.tar.gz
+./install-sh -o root -g root -m 0644 doc/reference/syslog-ng.txt \
+  ${RPM_BUILD_ROOT}/%{_prefix}/share/doc/syslog-ng-@VERSION@/syslog-ng.txt
+./install-sh -o root -g root -m 0644 ChangeLog \
+  ${RPM_BUILD_ROOT}/%{_prefix}/share/doc/syslog-ng-@VERSION@/ChangeLog
+./install-sh -o root -g root -m 0644 NEWS \
+  ${RPM_BUILD_ROOT}/%{_prefix}/share/doc/syslog-ng-@VERSION@/NEWS
+./install-sh -o root -g root -m 0644 README \
+  ${RPM_BUILD_ROOT}/%{_prefix}/share/doc/syslog-ng-@VERSION@/README
+./install-sh -o root -g root -m 0644 AUTHORS \
+  ${RPM_BUILD_ROOT}/%{_prefix}/share/doc/syslog-ng-@VERSION@/AUTHORS
+./install-sh -o root -g root -m 0644 COPYING \
+  ${RPM_BUILD_ROOT}/%{_prefix}/share/doc/syslog-ng-@VERSION@/COPYING
 
 %files
 %defattr(-,root,root)
-/sbin/syslog-ng
+%{prefix}/sbin/syslog-ng
+%{_mandir}/*
+%docdir %{_prefix}/share/doc/syslog-ng-@VERSION@
+%{_prefix}/share/doc/syslog-ng-@VERSION@/*
+%config(noreplace) /etc/syslog-ng/syslog-ng.conf
+%ifnos aix5.2
 /etc/rc.d/init.d/syslog-ng
-/usr/share/man/*
-%docdir /usr/share/doc/syslog-ng-@VERSION@
-/usr/share/doc/syslog-ng-@VERSION@/*
-%config /etc/syslog-ng/syslog-ng.conf
-%config /etc/logrotate.d/syslog-ng
+%config(noreplace) /etc/logrotate.d/syslog-ng
+%endif
 
 %post
+%ifos aix5.2
+echo "Checking whether the syslog-ng service is already registered... "
+if ! /usr/bin/lssrc -s syslogng >/dev/null 2>&1; then
+        echo "NO"
+        echo "Registering syslog-ng service... "
+        if /usr/bin/mkssys -s syslogng -p /opt/freeware/sbin/syslog-ng -u 0 \
+          -a '-F -p /etc/syslog-ng.pid' -O -d -Q -S -n 15 -f 9 -E 20 -G ras -w 2 \
+          >/dev/null 2>&1; then
+                echo "SUCCESSFUL"
+        else
+                echo "FAILED"
+        fi
+else
+        echo "YES"
+fi
+
+echo "Checking whether the syslogd service is registered..."
+if /usr/bin/lssrc -s syslogd >/dev/null 2>&1; then
+        echo "YES"
+        if /usr/bin/lssrc -s syslogd|grep -E "^ syslogd.*active" > /dev/null 2>&1; then
+                echo "Stopping the syslogd service..."
+                if /usr/bin/stopsrc -s syslogd >/dev/null 2>&1; then
+                        echo "SUCCESSFUL"
+                else
+                        echo "FAILED, continuing anyway"
+                fi
+        fi
+        echo "Disabling syslogd service"
+        if /usr/bin/rmssys -s syslogd >/dev/null 2>&1; then
+                echo "SUCCESSFUL"
+        else
+                echo "FAILED"
+        fi
+else
+        echo "NO"
+fi
+
+if /usr/bin/lssrc -s syslogng|grep -E "^ syslogng.*active" >/dev/null 2>&1; then
+        echo "Stopping syslog-ng"
+        /usr/bin/stopsrc -s syslogng
+fi
+echo "Starting syslog-ng"
+/usr/bin/startsrc -s syslogng
+#post end
+%else
+if [ "%{_host_vendor}" = "redhat" ]; then
+  sh /etc/rc.d/init.d/syslog stop || true
+elif [ "%{_host_vendor}" = "suse" ]; then
+  sh /etc/init.d/syslog stop || true
+  if [ -L /etc/init.d/syslog-ng ]; then
+    rm -f /etc/init.d/syslog-ng
+  fi
+  ln -s /etc/rc.d/init.d/syslog-ng /etc/init.d/syslog-ng
+fi
+chkconfig --del syslog
 chkconfig --add syslog-ng
 sh /etc/rc.d/init.d/syslog-ng start || exit 0
+%endif
 
 %preun
-sh /etc/rc.d/init.d/syslog-ng stop || exit 0
+%ifos aix5.2
+	if /usr/bin/lssrc -s syslogng >/dev/null 2>&1; then
+        	if /usr/bin/lssrc -s syslogng|grep -E "^ syslogng.*active" > /dev/null 2>&1; then
+                	echo "Stopping syslog-ng"
+	                /usr/bin/stopsrc -s syslogng
+	        fi
+        	echo "Unregistering syslog-ng"
+	        if /usr/bin/rmssys -s syslogng >/dev/null 2>&1; then
+        	        echo "SUCCESSFUL"
+	        else
+        	        echo "FAILED"
+	        fi
+	fi
+
+# re-enable the standard syslogd subsystem
+#subsysname:synonym:cmdargs:path:uid:auditid:standin:standout:standerr:action:multi:contact:svrkey:svrmtype:priority:sig norm:sigforce:display:waittime:grpname:
+# syslogd:::/usr/sbin/syslogd:0:0:/dev/console:/dev/console:/dev/console:-O:-Q:-K:0:0:20:0:0:-d:20:ras:
+
+	if ! /usr/bin/lssrc -s syslogd >/dev/null 2>&1; then
+        	echo "Registering syslogd service"
+	        if /usr/bin/mkssys -s syslogd -p /usr/sbin/syslogd -u 0 -O -Q -K -E 20 -d \
+        	  -G ras >/dev/null 2>&1; then
+	                echo "SUCCESSFUL"
+        	else
+                	echo "FAILED"
+	        fi
+	fi
+
+	if /usr/bin/lssrc -s syslogd >/dev/null 2>&1; then
+        	if ! /usr/bin/lssrc -s syslogd | grep -E "^ syslogd.*active" >/dev/null 2>&1; then
+	                echo "Starting syslogd"
+        	        /usr/bin/startsrc -s syslogd
+	        fi
+	fi
+#preun end
+%else
+sh /etc/rc.d/init.d/syslog-ng stop || exit 0 
+if [ "%{_host_vendor}" = "redhat" ]; then
+  sh /etc/rc.d/init.d/syslog start || true
+elif [ "%{_host_vendor}" = "suse" ]; then
+  if [ -L /etc/init.d/syslog-ng ]; then
+    rm -f /etc/init.d/syslog-ng
+  fi
+  sh /etc/init.d/syslog start || true
+fi
+%endif
 
 %postun
-chkconfig --del syslog-ng
+%ifnos aix5.2
+chkconfig --force --del syslog-ng
+chkconfig --add syslog
 
 %check
+%endif
+
 %clean
-[ $RPM_BUILD_ROOT == / ] || rm -rf $RPM_BUILD_ROOT
+[ $RPM_BUILD_ROOT = / ] || rm -rf $RPM_BUILD_ROOT
 
 %changelog
+* Wed Nov 22 2006 Tamas Pal <folti@balabit.com>
+- Added dependencies glib2-devel and pkgconfig.
+- Configfiles /etc/syslog-ng/syslog-ng.conf and /etc/logrotate.d/syslog-ng no
+  longer replaced blindly during upgrade.
+* Fri Nov 3 2006 Tamas Pal <folti@balabit.com>
+- Added SuSE packaging.
+- Added AIX 5.2 packaging.
+- Now provides syslog.
+- Added dependency libevtlog-devel.
 * Fri Jun 30 2006 Tamas Pal <folti@balabit.com>
 - fixed typo in RHEL config file.
 * Mon Mar 27 2006 Balazs Scheidler <bazsi@balabit.com>
@@ -101,3 +237,5 @@ chkconfig --del syslog-ng
 - added upstream's documentation to the package
 * Mon Jun 20 2005 Sandor Geller <wildy@balabit.com>
 - initial RPM packaging for RHEL ES
+
+# vim: ts=2 ft=spec
