dbld: add our dependency storage repo as fallback of download failures
Signed-off-by: Hofi <hofione@gmail.com>

diff --git a/dbld/builddeps b/dbld/builddeps
--- a/dbld/builddeps
+++ b/dbld/builddeps
@@ -90,7 +90,7 @@ function install_dbld_dependencies()
 function install_criterion() {
     CRITERION_VERSION=2.3.3
 
-    download_target "https://github.com/Snaipe/Criterion/releases/download/v${CRITERION_VERSION}/criterion-v${CRITERION_VERSION}.tar.bz2" /tmp/criterion.tar.bz2
+    download_target "https://github.com/Snaipe/Criterion/releases/download/v${CRITERION_VERSION}/criterion-v${CRITERION_VERSION}.tar.bz2" /tmp/criterion.tar.bz2 criterion/${CRITERION_VERSION}/criterion.tar.bz2
     cd /tmp/
     tar xvf /tmp/criterion.tar.bz2
     cd /tmp/criterion-v${CRITERION_VERSION}
@@ -108,7 +108,7 @@ function set_jvm_paths() {
 
 function install_gradle {
     GRADLE_VERSION=4.10
-    download_target "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" /tmp/gradle.zip
+    download_target "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" /tmp/gradle.zip gradle/${GRADLE_VERSION}/gradle.zip
     mkdir -p /opt/gradle
     unzip -d /opt/gradle /tmp/gradle.zip
     rm -rf /tmp/gradle.zip
@@ -118,14 +118,31 @@ function install_gradle {
 }
 
 function install_pip2 {
-    download_target "https://bootstrap.pypa.io/pip/2.7/get-pip.py" get-pip.py
+    PIP_VERSION=2.7
+    download_target "https://bootstrap.pypa.io/pip/${PIP_VERSION}/get-pip.py" get-pip.py pip/${PIP_VERSION}/get-pip.py
     python2 get-pip.py
 }
 
-function download_target() {
-    target=$1
-    output=$2
-    curl --location --insecure "$target" --output "$output"
+function download_target()
+{
+    TARGET=$1
+    OUTPUT=$2
+    FALLBACK_PATH=$3
+
+    # NOTE: Any new fallback packages must be uploaded to this repo, do not forget to maintain if needed!
+    #       Keep it version organized!
+    OSE_GIT_DOWNLOAD_REPO="https://github.com/syslog-ng/syslog-ng-deps/raw/main"
+
+    if ! curl --location --insecure --fail "$TARGET" --output "$OUTPUT"; then
+        if [ -n "$FALLBACK_PATH" ]; then
+            FALLBACK_URL="${OSE_GIT_DOWNLOAD_REPO}/${FALLBACK_PATH}"
+            echo "Primary download failed, trying fallback: $FALLBACK_URL"
+            curl --location --insecure --fail "$FALLBACK_URL" --output "$OUTPUT"
+        else
+            echo "Download failed and no fallback specified."
+            return 1
+        fi
+    fi
 }
 
 function filter_packages_by_platform {
@@ -286,7 +303,7 @@ function install_perf {
 function install_bison_from_source {
     BISON_VERSION=3.7.6
     cd /tmp
-    download_target https://ftp.gnu.org/gnu/bison/bison-${BISON_VERSION}.tar.gz /tmp/bison-${BISON_VERSION}.tar.gz
+    download_target https://ftp.gnu.org/gnu/bison/bison-${BISON_VERSION}.tar.gz /tmp/bison-${BISON_VERSION}.tar.gz bison/${BISON_VERSION}/bison.tar.gz
     tar xvfz /tmp/bison-${BISON_VERSION}.tar.gz
     cd /tmp/bison-${BISON_VERSION}
     ./configure --prefix=/usr/local --disable-nls
